id: P576514F1
initial_creation_type: input
source_metadata:
  title: Letters Series
  language: bo
  description: 'Examples of official and personal correspondence:'
  volume:
    85100832fd324d7a9c490d0f2dad8504:
      title: Letter of Advice to Jamyang Gyaltsen
      parent: Advice
    1527ff1813904ce3b2c7c45df74621f4:
      title: A Letter to the Fourteenth Dalai Lama, Supreme Victorious Guru of the
        Beings of the Three Realms
      parent: General
    22cf3cf123ab460798143ebc7383cbf2:
      title: Letter to Gyarong Khandro
      parent: General
created_at: '2022-03-01T04:10:27.889676'
last_modified_at: '2022-03-01T04:10:27.889679'
